- includes/class-piklist.php
- was seeing error about invalid index "order"; this happened when one of the two array elements being compared didn't have an ['args']['order'] element
- the code was returning zero only if both were not set
- changed && to || so that if either is not set, return value is 0
> fix invalid index in array compare

- includes/class-piklist-add-on.php
- includes/class-piklist-shortcode.php
Under Windows, debug_backtrace() returns paths with backslashes. Added
code to normalize so function works and shortcode editor does not break. #18 
Also added fix for #20 (when using shortcuts with no arguments or content)
> Fix empty shortcut editor when on Windows server

- includes/class-piklist-admin.php
WooCommerce does something fancy where the parent url of the submenu items to the WooCommerce menu is 'woocommerce'. So they're doing something fancy in the admin_menu chain.
Currently we're hooking into -1, which is very likely happening before the hook. By removing that and letting the menu fall back on the default of 10 everything starts working.
I'm not aware of any reason why a priority of -1 was used. I know priorities in Piklist used to be more of a delicate balance, but I believe things are more robust, now.
Any issues with this? I can see others wanting to set custom setting pages inside the WooCommerce menu.
> Fix ability to add submenu pages in WooCommerce

- includes/class-piklist-cpt.php
Rewrite the post_updated_messages_filter function to support CPT that are not publicly_queryable. If publicly_queryable = false, we don't have to show the preview post link, scheduled post link and the view post link.
This fixes this issue I reported:
https://github.com/piklist/piklist/issues/53
> Rewrite the post_updated_messages_filter

- includes/class-piklist-add-on.php
- includes/class-piklist-admin.php
- includes/class-piklist-theme.php
- parts/admin-pages/welcome.php
ISSUE: When Piklist has dependent plugins or theme, we disable the "deactivate" link on the plugin. This has caused lots of confusion, even though we show a message: "Dependent plugins or theme are active."
UPDATES: This PR does a few  things:
1) Change piklist_admin::$piklist_dependent to an array that will store the names of the dependent plugins or theme.
2) Update the welcome.php to show the dependencies list if available.
3) Make the message "Dependent plugins or theme are active." a link to the Welcome page  listing the dependencies.
> update piklist_admin::$piklist_dependent to store dependent theme and plugins

- includes/class-piklist-admin.php
When using the piklist_admin_pages filter, if no capability is set, the page doesn't even show up.
```
add_filter('piklist_admin_pages', 'my_admin_pages');
function my_admin_pages($pages) {
$pages[] = array(
'page_title' => __('About this plugin', 'piklist')
,'menu_title' => __('About', 'piklist')
,'menu_slug' => 'about_my_plugin'
);
return $pages;
}
```
I propose setting a default capability of `manage_options`.
> set default capability on admin pages

- includes/class-piklist-form.php
Right now there is no way to add custom field aliases, so I added a filter to do that, in a similar way to what you do with field_list_types
> Added a filter to allow setting custom field aliases

- includes/class-piklist-help.php
- includes/class-piklist-media.php
- includes/class-piklist-meta.php
- includes/class-piklist-notice.php
- includes/class-piklist-pointer.php
- includes/class-piklist-taxonomy.php
- includes/class-piklist-user.php
- includes/class-piklist-workflow.php
- includes/class-piklist.php
This PR extends the "ID" parameter in the Piklist comment blocks so other individual parts can be targeted, in addition to a page. It also adds the "Slug" parameter for targeting of an individual page, term, user, help, media, notice or pointer. With user, the "slug" is the "user ID"
> Comment block updates

- parts/js/piklist.js
Currently there's no good way of knowing, in js, when files have been added or removed from the file field. I have a use for this and it seems a sensible addition so other code can interact with the field at key events.
> Add javscript triggers for adding and removing in file field

- includes/class-piklist-cpt.php
I suggest we use the WordPress defaults for register_post_status when registering custom statuses in Piklist. EXCEPT 'show_in_admin_status_list'. WordPress sets this to `null` by default, and we currently have it set to `true`:
https://build.trac.wordpress.org/browser/tags/4.9.5/wp-includes/post.php#L792
If we go with the WordPress default of `null`, posts may disappear from list tables around the world for users that did not use that parameter when registering their custom statuses. Leaving this for backwards compatibility.
> Use WordPress defaults for register_post_status except 'show_in_admin_status_list'

- includes/class-piklist-form.php
- includes/class-piklist-validate.php
- parts/js/piklist.js
This fixes this issue:
https://github.com/piklist/piklist/issues/60
In the method validate_value_callback, if the $field['request_value'] is not an array, the code performs an if ($field['request_value']) before running validation. For add-more fields however, the code goes straight to perform the validation. So I changed this behaviour.
This makes the code work, but the code on the client side for current add more fields, marks all inputs from the add more field are as wrong even only one of them is wrong. The current validation code stores the information about the index that failed, so I passed it to the client side and updated the javascript code to use that information.
Now it seems to work fine. Please take a look and tell me something about it! Thanks.
> Fix validation with add more fields

- add-ons/piklist-demos/piklist-demos.php
- includes/class-piklist-relate.php
The way additional query parameters are supported were changed when the REST API was merged into core in 4.7. This begins to fix that issue and so far allows for `post_has` and `post_belongs` to be used in the query.
Important Note: The `relate_query` parameter was not added on purpose. It's easy to sanitize `post_has` and `post_belongs`, but `relate_query` is a complex collection. Furthermore, it's worth considering that if something more complex is needed, the developer at that time should probably make their own query var that builds the `relate_query` itself. This reduces the complexity of the query and improves security.
I'm very interested in anyones thoughts that would like to chime in.
> Update relate query support to WordPress 4.7 standards

- includes/class-piklist-admin.php
There's a bug wherein the version stored in the options table for plugins is casted as a number of numeric. So 0.10, for example, becomes 0.1. In versioning these are not the same.
> Fix version checking for upgrades

- includes/class-piklist-form.php
This should fix the error here: https://piklist.com/support/topic/piklist-0-11-3-media-upload-multiple-images/
@sbruner Please look over this. I saw that you had a comment that booleans are being removed. It was doing `$value !== true`, but if all booleans are being removed then I figured `!is_bool($value)` makes sense (also removes false). Does this make sense and fit the context?
Please test this before merging.
> Fixing Media Upload Images Error

- includes/class-piklist-form.php
- piklist.php
- readme.txt
This allows developers to have forms that a non-logged in user can post content to (e.g. contact forms).
It seems we already have code for the user role and capability 'none' in Piklist, that's why this works:
https://github.com/piklist/piklist/blob/develop/includes/class-piklist-form.php#L3199
https://github.com/piklist/piklist/blob/develop/includes/class-piklist-form.php#L3280
https://github.com/piklist/piklist/blob/develop/includes/class-piklist-form.php#L3467
https://github.com/piklist/piklist/blob/develop/includes/class-piklist-form.php#L3730
> Allow user with no role set to save

- parts/shared/admin-workflow.php
ISSUE:
$active['parts'] is only set when a workflow has subtabs set. On pages with no subtabs, like `wp-admin/admin.php?page=piklist-core-settings` you get a warning.
SOLUTION:
Move the `foreach ($active['parts'] as $order => $part):` loop into the `if (isset($active['parts'])):` check
TEST:
You can test by visiting any workflow page with subtabs, and `wp-admin/admin.php?page=piklist-core-settings`
> move into isset($active['parts'] check

- includes/class-piklist-setting.php
It seems that `tab_order` is not used anymore. To consolidate parameters we replaced it with the existing 'order' parameter
> replace tab_order with order

- includes/class-piklist.php
- readme.txt
When saving user data on a page like this:
/wp-admin/user-edit.php?user_id=5
WordPress first redirects the page to:
/wp-admin/user-edit.php
which temporarily removes the query parameter from the url and throws a notice.
> when saving user data, check if $_GET['user_id'] is set before validating user

- includes/class-piklist-revision.php
Using `post_id` in a `WHERE` clause speeds up the `DISTINCT` query by ~50-70% in my profiling with a million rows postmeta table.
Uses `$post` param (added in WordPress 4.5.0), if available, otherwise uses global `$post` object through `get_post()`.
One edge case that I could think of is when a new meta is added to post. This meta maybe already applied to other posts of similar types so the `meta_key` would be there in the postmeta table. But by adding `WHERE` clause we will not know about it until that meta is updated in future for this post.
Another solution is to cache the current `DISTINCT` query in a transient and invalidate it by hooking into `added_post_meta`.
See #115
> Add post_id in a WHERE clause to speed up DISTINCT query.

- parts/js/admin.js
Making sure the post saves if no TinyMCE was found on the page. For example, when a Frontend Editor mode is used in WPBakery Visual Composer Page editor together with Piklist, the post does not save and the following error gets triggered:
```
admin.js?ver=1.0.4:436 Uncaught TypeError: Cannot read property 'selection' of null
at HTMLDocument.<anonymous> (admin.js?ver=1.0.4:436)
at HTMLDocument.dispatch (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=5.2:3)
at HTMLDocument.r.handle (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=5.2:3)
at Object.trigger (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=5.2:3)
at Object.a.event.trigger …
```
> Making sure the post saves if no TinyMCE was found

- includes/class-piklist-meta.php
- piklist.php
- readme.txt
check if !empty($meta_box['id']) && !empty($part['id'].
Was throwing this error in PHP 7.4
`Notice: Trying to access array offset on value of type null in /var/www/example.com/public_html/wp-content/plugins/piklist/includes/class-piklist-meta.php`
> FIXED: PHP 7.4 notice for Dashboard / CPT meta boxes
